"""Actualizacion tabla carro_compras idUsuario no unique

Revision ID: 57467d0908da
Revises: 1abe57cb74b9
Create Date: 2025-06-06 22:04:35.925503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57467d0908da'
down_revision = '1abe57cb74b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carro_compras', schema=None) as batch_op:
        batch_op.drop_constraint('carro_compras_idUsuario_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carro_compras', schema=None) as batch_op:
        batch_op.create_unique_constraint('carro_compras_idUsuario_key', ['idUsuario'])

    # ### end Alembic commands ###
