"""Actualizacion tabla carro_compras idUsuario nullable=true

Revision ID: 8d3bc507cef8
Revises: 57467d0908da
Create Date: 2025-06-06 22:18:36.436213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3bc507cef8'
down_revision = '57467d0908da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carro_compras', schema=None) as batch_op:
        batch_op.alter_column('idUsuario',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carro_compras', schema=None) as batch_op:
        batch_op.alter_column('idUsuario',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
