"""Hacer idUsuario NOT NULL

Revision ID: ca9ac16f2948
Revises: fe2d341303e1
Create Date: 2025-05-24 18:38:18.168301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9ac16f2948'
down_revision = 'fe2d341303e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carro_compras', schema=None) as batch_op:
        batch_op.alter_column('idUsuario',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carro_compras', schema=None) as batch_op:
        batch_op.alter_column('idUsuario',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
