"""crear tablas

Revision ID: cf9ebe085814
Revises: 
Create Date: 2025-05-05 19:19:48.677483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf9ebe085814'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carro_compras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('precio', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('imagen', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_carro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idProductos', sa.Integer(), nullable=False),
    sa.Column('idCarro', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idCarro'], ['carro_compras.id'], ),
    sa.ForeignKeyConstraint(['idProductos'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreUsuario', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=10), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('detalleDireccion', sa.String(length=200), nullable=False),
    sa.Column('cedula', sa.String(length=10), nullable=False),
    sa.Column('idCarroCom', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idCarroCom'], ['carro_compras.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idCarroCom')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido')
    op.drop_table('item_carro')
    op.drop_table('productos')
    op.drop_table('carro_compras')
    # ### end Alembic commands ###
