"""Actualizacion tabla productos y creacion tablas criterio

Revision ID: ee2217677b7e
Revises: a9036ee6f985
Create Date: 2025-06-01 17:19:21.064092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee2217677b7e'
down_revision = 'a9036ee6f985'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('marca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marca', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('talla',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talla', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagenPrin', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('imagenesDet', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('idCategoria', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('idMarca', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('idTalla', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['idCategoria'])
        batch_op.create_unique_constraint(None, ['idMarca'])
        batch_op.create_unique_constraint(None, ['idTalla'])
        batch_op.create_foreign_key(None, 'talla', ['idTalla'], ['id'])
        batch_op.create_foreign_key(None, 'categoria', ['idCategoria'], ['id'])
        batch_op.create_foreign_key(None, 'marca', ['idMarca'], ['id'])
        batch_op.drop_column('imagen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagen', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('idTalla')
        batch_op.drop_column('idMarca')
        batch_op.drop_column('idCategoria')
        batch_op.drop_column('imagenesDet')
        batch_op.drop_column('imagenPrin')

    op.drop_table('talla')
    op.drop_table('marca')
    op.drop_table('categoria')
    # ### end Alembic commands ###
