"""Migración inicial con usuarios, favoritos y relación CarroCompras

Revision ID: fe2d341303e1
Revises: 
Create Date: 2025-05-24 13:33:02.644662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2d341303e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombreUsu', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=10), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=10), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('detDireccion', sa.String(length=200), nullable=False),
    sa.Column('cedula', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idProductos', sa.Integer(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idProductos'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('carro_compras', schema=None) as batch_op:
        batch_op.add_column(sa.Column('idUsuario', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['idUsuario'])
        batch_op.create_foreign_key(None, 'usuarios', ['idUsuario'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carro_compras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('idUsuario')

    op.drop_table('favoritos')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
